name: Deploy UpdateOrder
on:
  push:
    branches:
      - main
    paths:
      - 'functions/updateOrder/**'

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      function_name: updateOrder

  deploy:
    needs: build-test
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: updateOrder
      environment: prod
      dynamo_table_name: orders
      api_id: o6moxkl86j